# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=140)),
                ('telefono', models.CharField(max_length=13)),
                ('telefono_alterno', models.CharField(blank=True, max_length=16, null=True)),
                ('correo', models.EmailField(max_length=140)),
                ('correo_alterno', models.EmailField(blank=True, max_length=140, null=True)),
                ('tamano', models.CharField(max_length=10)),
                ('plazo', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('ubicacion', models.TextField()),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', 'hora'),
            },
        ),
    ]
