# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20170210_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tamano',
            field=models.CharField(max_length=50),
        ),
    ]
