# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20170210_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ('-fecha', '-hora')},
        ),
    ]
