# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20170210_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
