# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20160928_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
