# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_auto_20160928_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
