# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_auto_20160927_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('-fecha', '-hora')},
        ),
        migrations.AddField(
            model_name='cliente',
            name='hora',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
