# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_auto_20160927_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
    ]
