# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_auto_20160929_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
