# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_cliente_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cita',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
