# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0010_cliente_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
