# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_auto_20170131_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administradores',
        ),
    ]
