# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0013_comentarios_comentador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('verde', 'Contactado'), ('amarillo', 'En proceso'), ('rojo', 'Sin atender')], default='rojo', max_length=10),
        ),
    ]
