# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0014_cliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(blank=True, choices=[('verde', 'Contactado'), ('amarillo', 'En proceso'), ('rojo', 'Sin atender')], default='rojo', max_length=10, null=True),
        ),
    ]
